variables:
  REPO_NAME: []
stages:
  - setup
  - compile
  - imagebuild
  - deploy

compile_dev:
  image: node:18
  stage: compile
  tags:
    - redrock
  script:
    - npm i pnpm -g
    - pnpm install
    - pnpm run build
  artifacts:
    expire_in: 3 days
    paths:
      - build
  only:
    - dev/test

compile_prod:
  image: node:18
  stage: compile
  tags:
    - redrock
  script:
    - npm i pnpm -g
    - pnpm install
    - pnpm run build
  artifacts:
    expire_in: 1 week
    paths:
      - build
  only:
    - master

image_dev:
  stage: imagebuild
  image: reg.redrock.team/base/redrock-helmetci-builder:latest
  tags:
    - redrock
  variables:
    NAMESPACE: fe-dev
  script:
    - '/kaniko/dockerfile-web.sh' # 生成 Dockerfile
    - '/kaniko/build-upload --no-ccr' # 不上传云
  only:
    - dev/test

image_prod:
  stage: imagebuild
  image: reg.redrock.team/base/redrock-helmetci-builder:latest
  tags:
    - redrock
  variables:
    NAMESPACE: fe-prod
  script:
    - '/kaniko/dockerfile-web.sh' # 生成 Dockerfile
    - '/kaniko/build-upload --no-ccr' #不上云
  only:
    - master

deploy_dev:
  stage: deploy
  image: reg.redrock.team/base/redrock-helmetci-deployer:latest
  tags:
    - redrock
  variables:
    REDROCK_HELM_CHART: base/local-app
    REDROCK_KUBECONFIG: $REDROCK_LOCAL_KUBECONFIG
    REDROCK_NAMESPACE: fe-dev
  script:
    - deploy --set "service[0].name=port0,service[0].protocol=http,service[0].port=8080"
  only:
    - dev/test

deploy_prod:
  stage: deploy
  image: reg.redrock.team/base/redrock-helmetci-deployer:latest
  tags:
    - redrock
  variables:
    REDROCK_HELM_CHART: base/local-app
    REDROCK_KUBECONFIG: $REDROCK_LOCAL_KUBECONFIG
    REDROCK_NAMESPACE: fe-prod
  script:
    - deploy --set "service[0].name=port0,service[0].protocol=http,service[0].port=8080"
  only:
    - master
